# Generated by Django 5.2.3 on 2025-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('Blue', 'Blue'), ('Black', 'Black'), ('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red'), ('Yellow', 'Yellow')], max_length=50)),
            ],
        ),
    ]
